INSERT INTO Courses VALUES('BS11001','Biomolecules');
INSERT INTO Courses VALUES('BS11002',' Evolution of Cells');
INSERT INTO Courses VALUES('BS11004','Laboratory and Research Skills 1B');
INSERT INTO Courses VALUES('BS11003','Laboratory and Research Skills 1A');
INSERT INTO Courses VALUES('BS12001','Genes and Hereditary');
INSERT INTO Courses VALUES('BS12003','Laboratory and  Research Skills 1C');
INSERT INTO Courses VALUES('BS12004','Laboratory and Research Skills 1D');
INSERT INTO Courses VALUES('BS11005','Numeracy, Chemistry and Physics for the Biological and Biomedical Sciences');
INSERT INTO Courses VALUES('BS11006','The Poison Pen');
INSERT INTO Courses VALUES('BS12005','Science in Society');
INSERT INTO Courses VALUES('BS12008','Introduction to Scientific Enterprise');
INSERT INTO Courses VALUES('BS12009','Fundamentals of Organic Chemistry');
INSERT INTO Courses VALUES('BS12002','Origin of Animal Organ Systems');
INSERT INTO Courses VALUES('BS21001','Statistics and Experimental Design');
INSERT INTO Courses VALUES('BS21002','Cellular Communication');
INSERT INTO Courses VALUES('BS21003','Laboratory and Research Skills 2A');
INSERT INTO Courses VALUES('BS21004','Laboratory and Research Skills 2B');
INSERT INTO Courses VALUES('BS21008','Organic Chemistry for the Life Science');
INSERT INTO Courses VALUES('BS21009','Data analysis for the Life Science');
INSERT INTO Courses VALUES('BS21010','Introductory Programming for Life Sciences');
INSERT INTO Courses VALUES('BS21011','Developing Scientific Enterprise');
INSERT INTO Courses VALUES('BS22001','Human Physiology and Pharmacology');
INSERT INTO Courses VALUES('BS22002','Biomolecular Mechanisms');
INSERT INTO Courses VALUES('BS22003','Laboratory and Research Skills 2C');
INSERT INTO Courses VALUES('BS31003','Molecular Structure & Interactions');
INSERT INTO Courses VALUES('BS31004','Biochemistry & Cell Biology');
INSERT INTO Courses VALUES('BS31005','Genetics');
INSERT INTO Courses VALUES('BS31006','Gene Regulation & Expression');
INSERT INTO Courses VALUES('BS31013','Biomembranes');
INSERT INTO Courses VALUES('BS31016','Practical Techniques in Biomedical Sciences (BMS)');
INSERT INTO Courses VALUES('BS31019','Regulatory Physiology & Pharmacology (BMS)');
INSERT INTO Courses VALUES('BS31020','Experimental Cell Culture (BMS)');
INSERT INTO Courses VALUES('BS32003','Drug Discovery and Developmenent');
INSERT INTO Courses VALUES('BS32004','Molecular Microbiology');
INSERT INTO Courses VALUES('BS32005','Cell & Developmental Biology');
INSERT INTO Courses VALUES('BS32006','Cell Signalling');
INSERT INTO Courses VALUES('BS32007','Organic Synthesis');
INSERT INTO Courses VALUES('BS32008','Plant Science');
INSERT INTO Courses VALUES('BS32009','Immunology');
INSERT INTO Courses VALUES('BS32010','Applied Bioinformaticts');
INSERT INTO Courses VALUES('BS32011','Practical Project');
INSERT INTO Courses VALUES('BS32012','Practical Project');
INSERT INTO Courses VALUES('BS32020','Human Epithelial Biology');
INSERT INTO Courses VALUES('BS32021','Quantitative Pharmacology');
INSERT INTO Courses VALUES('BS32024','Neuropsychopharmacology');
INSERT INTO Courses VALUES('BS32026','Sensory & Motorneuroscience');
INSERT INTO Courses VALUES('BS32028','Molecular Pharmacologts');
INSERT INTO Courses VALUES('BS32029','Cell Proliferation and Survival Mechanisms Underlying Disease');
INSERT INTO Courses VALUES('BS32030','Data and Statistical Analysis');
INSERT INTO Courses VALUES('BS32031','Bioinformatics Research Skills 1');
INSERT INTO Courses VALUES('BS32032','Science Communication');
INSERT INTO Courses VALUES('BS41004/07','Research Project');
INSERT INTO Courses VALUES('BS41005/06','Research Skills');
INSERT INTO Courses VALUES('BS42003','Advanced Bioinformatics');
INSERT INTO Courses VALUES('BS42004','Advanced Modern Drug Discovery');
INSERT INTO Courses VALUES('BS42005','Advanced Plant Sciences');
INSERT INTO Courses VALUES('BS42006','Advanced Immunology');
INSERT INTO Courses VALUES('BS42007','Cancer Biology');
INSERT INTO Courses VALUES('BS42008','Stem Cells in Development and Disease');
INSERT INTO Courses VALUES('BS42009','Advanced Molecular Microbiology');
INSERT INTO Courses VALUES('BS42010','Advanced Gene Regulation & Expression');
INSERT INTO Courses VALUES('BS42011','Advanced Organic Chemistry');
INSERT INTO Courses VALUES('BS42012','Parasitology');
INSERT INTO Courses VALUES('BS42013','Advanced Cell Signalling');
INSERT INTO Courses VALUES('BS42014','Nutrients and Metabolic Disease');
INSERT INTO Courses VALUES('BS42017','Translational Psychiatry & Neurology');
INSERT INTO Courses VALUES('BS42018','Synaptic Plasticity and Cognition');
INSERT INTO Courses VALUES('BS42019','Cardiovascular Pharmacology');
INSERT INTO Courses VALUES('BS42021','Heart and Circulation');
INSERT INTO Courses VALUES('BS42023','Applied Neuroanatomy & Neurodegenerative Disorders');
INSERT INTO Courses VALUES('BS42025','The Conscious Brain: The Physiology & Pharmacology of Pain & Anaesthesia');
INSERT INTO Courses VALUES('BS42027','Cancer Pharmacology and Treatment');
INSERT INTO Courses VALUES('BS42028','Pharmacology of Treatment of Metabolic Disease');
INSERT INTO Courses VALUES('BS52008','Project Proposal and Associated Skills');
INSERT INTO Courses VALUES('BS52009','Therapeutics');
INSERT INTO Courses VALUES('BS53003','MSc Bio-business Research Project');
INSERT INTO Courses VALUES('BS51008','Molecular Basis of Diseases: Genetics, Epigenetics and Genomics');
INSERT INTO Courses VALUES('BS51007','Cell Biology and Disease');
INSERT INTO Courses VALUES('BS52007','Advanced Technology Platforms');
INSERT INTO Courses VALUES('BS53004','MSc Research Project');
INSERT INTO Courses VALUES('BU11001b','Introductory Financial Accounting');
INSERT INTO Courses VALUES('BU11002','International Business Environment');
INSERT INTO Courses VALUES('BU11003','Management and Information Systems');
INSERT INTO Courses VALUES('BU11005','Step-up to Business');
INSERT INTO Courses VALUES('BU12001','Introductory Management Accounting');
INSERT INTO Courses VALUES('BU12003','Accounting for non-specialists');
INSERT INTO Courses VALUES('BU12005','Foundations of Economics Analysis');
INSERT INTO Courses VALUES('BU12006','Fundamentals of Marketing');
INSERT INTO Courses VALUES('BU12008','Digital Business and Innovation');
INSERT INTO Courses VALUES('BU12004','Foundations of Economic Analysis');
INSERT INTO Courses VALUES('BU11004','Global Economic Perspectives');
INSERT INTO Courses VALUES('BU11006','Specialist Management English for Business 1');
INSERT INTO Courses VALUES('BU12007','Specialist Management English for Business 2');
INSERT INTO Courses VALUES('BU21006','Economics of an unequal world');
INSERT INTO Courses VALUES('BU22008','Customer Experience in a Digital World');
INSERT INTO Courses VALUES('BU21007','Emerging Tecnologies:the Digital Business Environment');
INSERT INTO Courses VALUES('BU21002','Intermediate Financial Accounting');
INSERT INTO Courses VALUES('BU21003','Managing People in Organisations');
INSERT INTO Courses VALUES('BU21001','Financial Decision Analysis');
INSERT INTO Courses VALUES('BU21004','Microeconomics');
INSERT INTO Courses VALUES('BU22001','Business Law');
INSERT INTO Courses VALUES('BU22002','Intermediate Management Accounting');
INSERT INTO Courses VALUES('BU22003','Intermediate Financial Management');
INSERT INTO Courses VALUES('BU22005','Macroeconomics and Economic Statistics');
INSERT INTO Courses VALUES('BU22007','Project Management');
INSERT INTO Courses VALUES('BU32004','Managing Successful New Business Ventures');
INSERT INTO Courses VALUES('BU32005','Operations Management in SMEs');
INSERT INTO Courses VALUES('BBU300001','Advanced Financial Accounting');
INSERT INTO Courses VALUES('BU30002','Advanced Financial Management');
INSERT INTO Courses VALUES('BBU30003','Advanced Management Accounting');
INSERT INTO Courses VALUES('BU30004','Auditing');
INSERT INTO Courses VALUES('BU30005','Taxation');
INSERT INTO Courses VALUES('BU30006','Financial Reporting Theory');
INSERT INTO Courses VALUES('BU30011','Examining Business Information Systems');
INSERT INTO Courses VALUES('BU30007','International Capital Markets');
INSERT INTO Courses VALUES('BU30010','Research Methods and Consultancy Practices');
INSERT INTO Courses VALUES('BU30008','Strategic Management and Leadership');
INSERT INTO Courses VALUES('BU30013','Marketing');
INSERT INTO Courses VALUES('BU31002','Principles of Econometrics');
INSERT INTO Courses VALUES('BU32002','Applied Econometrics');
INSERT INTO Courses VALUES('BU30022','Behavioural Economics');
INSERT INTO Courses VALUES('BU30013b','Marketing');
INSERT INTO Courses VALUES('BU30014','Financial Institutionsr');
INSERT INTO Courses VALUES('BU30015','Principles of Human Resources Management');
INSERT INTO Courses VALUES('BU31006','Principles of Human Resource Management');
INSERT INTO Courses VALUES('BU30016','Microeconomic Analysis');
INSERT INTO Courses VALUES('BU30017','Macroeconomic Analysis');
INSERT INTO Courses VALUES('BU30018','Marketing Strategy');
INSERT INTO Courses VALUES('BU30019','Quantitative Methods for Business');
INSERT INTO Courses VALUES('BU40008','Managing Human Rights');
INSERT INTO Courses VALUES('BU40005','Financial Statement Analysis');
INSERT INTO Courses VALUES('BU40001','Social Responsibility');
INSERT INTO Courses VALUES('BU40006','Fiscal Studies');
INSERT INTO Courses VALUES('BU40013','The Business of Human Rights');
INSERT INTO Courses VALUES('BU40013a','The Business of Human Rights 2');
INSERT INTO Courses VALUES('BU41007','Contemporary Issues in International Reporting');
INSERT INTO Courses VALUES('BU41004','Security Analysis');
INSERT INTO Courses VALUES('BU42002','Corporate Restructuring and Finance');
INSERT INTO Courses VALUES('BU42003','Portfolio Management');
INSERT INTO Courses VALUES('BU42007','Financial Assurance and Ethics');
INSERT INTO Courses VALUES('BU40009','Change Management');
INSERT INTO Courses VALUES('BU40014','Understanding and Managing Organisational Space');
INSERT INTO Courses VALUES('BU40010','Issues in Management Accounting Research');
INSERT INTO Courses VALUES('BU40011','Business Management Dissertation');
INSERT INTO Courses VALUES('BU40012','Business Consultancy Project');
INSERT INTO Courses VALUES('BU40015','Government and Business');
INSERT INTO Courses VALUES('BU40016','Economics of Globalisation');
INSERT INTO Courses VALUES('BU40017','International Finance');
INSERT INTO Courses VALUES('BU40018','Risk and Information');
INSERT INTO Courses VALUES('BU40019','Business Strategy');
INSERT INTO Courses VALUES('BU41020','Microeconomic Policy');
INSERT INTO Courses VALUES('BU42020','Macroeconomic Policy');
INSERT INTO Courses VALUES('BU42021','Microeconomic Theory');
INSERT INTO Courses VALUES('BU41021','Macroeconomic Theory');
INSERT INTO Courses VALUES('BU40022','Financial Economic Analysis');
INSERT INTO Courses VALUES('BU41023','Principles of Marketing Research');
INSERT INTO Courses VALUES('BU40025','Marketing Research Project');
INSERT INTO Courses VALUES('BU41005','Accounting & Accountability in the Public Sector');
INSERT INTO Courses VALUES('BU41002','Corporate Governance');
INSERT INTO Courses VALUES('BU42008','Branding and Marketing for Transitional Change');
INSERT INTO Courses VALUES('BU11001','Introductory Financial Accounting');
INSERT INTO Courses VALUES('BU99992','Doing Business in Scotland');
INSERT INTO Courses VALUES('BU99996','Doing Business in Europe');
INSERT INTO Courses VALUES('BU99995','Big Data Analytics for Business Transformation');
INSERT INTO Courses VALUES('BU99993','Business in Society: Responsibility, Diversity and Geopolitics');
INSERT INTO Courses VALUES('BU99997','Rethinking Leadership');
INSERT INTO Courses VALUES('BU99998','Sustainable Supply Chain Management');
INSERT INTO Courses VALUES('BU99999','Business Start-up');
INSERT INTO Courses VALUES('BBU999910','Managing Teams and Individuals in a multicultural world');
INSERT INTO Courses VALUES('BBU999911','Emerging technologies - digital business environment');
INSERT INTO Courses VALUES('BBU999912','Applied Human Resource Management');
INSERT INTO Courses VALUES('BBU999913','Creative Intervention for Change and Innovation');
INSERT INTO Courses VALUES('BBU999914','Strategic Management in the 21st Century');
INSERT INTO Courses VALUES('BBU999915','Management Concepts in Context');
INSERT INTO Courses VALUES('AC11001','Introduction to Software Development');
INSERT INTO Courses VALUES('AC11002','Web Authoring');
INSERT INTO Courses VALUES('AC12001','Introduction to Data Structures and Algorithms');
INSERT INTO Courses VALUES('AC12003','Argumentation');
INSERT INTO Courses VALUES('AC21007','Algorithms and AI');
INSERT INTO Courses VALUES('AC21008','Multi-Paradigm Programming');
INSERT INTO Courses VALUES('AC21009','Computer Systems 2A : Architecture Fundamentals and Unix');
INSERT INTO Courses VALUES('AC21011','Creative Interactions');
INSERT INTO Courses VALUES('AC21012','Users and Interfaces');
INSERT INTO Courses VALUES('AC22004','Object Oriented Analysis and Design');
INSERT INTO Courses VALUES('AC22005','Computer Systems 2B: Architecture and Operating Systems');
INSERT INTO Courses VALUES('AC22006','Physical Computing');
INSERT INTO Courses VALUES('AC22007','Data Structures and Algorithms');
INSERT INTO Courses VALUES('AC31007','Agile Software Engineering');
INSERT INTO Courses VALUES('AC31008','Networks and Data Communications');
INSERT INTO Courses VALUES('AC31009','Games Programming');
INSERT INTO Courses VALUES('AC32005','Human Computer Interaction');
INSERT INTO Courses VALUES('AC32006','Database Systems');
INSERT INTO Courses VALUES('AC31012','Information Security');
INSERT INTO Courses VALUES('AC32007','Secure Internet Programming');
INSERT INTO Courses VALUES('AC32008','Theory of Computation');
INSERT INTO Courses VALUES('AC40001','Individual Project');
INSERT INTO Courses VALUES('AC41001','Graphics');
INSERT INTO Courses VALUES('AC41002','Computer Vision');
INSERT INTO Courses VALUES('AC41004','Industrial Team Project');
INSERT INTO Courses VALUES('AC41007','Technology Innovation Management');
INSERT INTO Courses VALUES('AC41010','Work Placement');
INSERT INTO Courses VALUES('AC41011','Big Data Analysis');
INSERT INTO Courses VALUES('AC41012','User Experience');
INSERT INTO Courses VALUES('AC42001','Research Frontiers');
INSERT INTO Courses VALUES('AC42002','Research Frontiers 2');
INSERT INTO Courses VALUES('AC50001','Introduction to Data Mining and Machine Learning');
INSERT INTO Courses VALUES('AC50002','Programming Languages for Data Engineering');
INSERT INTO Courses VALUES('AC52013','Human Computer Interaction');
INSERT INTO Courses VALUES('AC51002','Software Development');
INSERT INTO Courses VALUES('AC51003','Software Engineering');
INSERT INTO Courses VALUES('AC51004','Agile Engineering');
INSERT INTO Courses VALUES('AC51005','Technology Innovation Management');
INSERT INTO Courses VALUES('AC51007','Computer Vision');
INSERT INTO Courses VALUES('AC51008','Graphics');
INSERT INTO Courses VALUES('AC51010','User Experience');
INSERT INTO Courses VALUES('AC51011','Big Data Analysis');
INSERT INTO Courses VALUES('AC51039','User Experience');
INSERT INTO Courses VALUES('AC51041','DevOps and Microservices');
INSERT INTO Courses VALUES('AC52001','Database Systems');
INSERT INTO Courses VALUES('AC52002','Advanced Programming Techniques');
INSERT INTO Courses VALUES('AC52008','Research Frontiers (Computing)');
INSERT INTO Courses VALUES('AC51042','Information Security');
INSERT INTO Courses VALUES('AC52010','MSc Project');
INSERT INTO Courses VALUES('AC52012','Research Methods');
INSERT INTO Courses VALUES('AC52038','Business Intelligent Systems');
INSERT INTO Courses VALUES('AC52039','Transactional Database Models and Design');
INSERT INTO Courses VALUES('AC52040','Analytical Database Models and Design');
INSERT INTO Courses VALUES('AC52043','Big Data Analysis');
INSERT INTO Courses VALUES('AC52044','Research Frontiers');
INSERT INTO Courses VALUES('AC52048','Business Intelligent Systems');
INSERT INTO Courses VALUES('AC53001','Research Project');
INSERT INTO Courses VALUES('AC53005','MDX');
INSERT INTO Courses VALUES('AC53006','BI Research Project');
INSERT INTO Courses VALUES('AC53007','Field Project');
INSERT INTO Courses VALUES('AC53008','ETL-Theory and practice');
INSERT INTO Courses VALUES('AC53009','Data Analysis and Visualisation');
INSERT INTO Courses VALUES('AC53010','Advanced Statistics and Data Mining');
INSERT INTO Courses VALUES('LW11010','Foundations of Law');
INSERT INTO Courses VALUES('LW11011','Private Law of Scotland 1');
INSERT INTO Courses VALUES('LW11012','Public Law I - Sources of Power');
INSERT INTO Courses VALUES('LW12010','Scots Criminal Law & Evidence');
INSERT INTO Courses VALUES('LW12011','Private Law of Scotland II');
INSERT INTO Courses VALUES('LW12012','Public Law II: Controls on Power');
INSERT INTO Courses VALUES('LW21002','Commercial Law');
INSERT INTO Courses VALUES('LW21003','Scottish Property Law');
INSERT INTO Courses VALUES('LW21013','Foundations of Law (Advanced)');
INSERT INTO Courses VALUES('LW21014','English Law of Contract');
INSERT INTO Courses VALUES('LW21015','Public Law I (Advanced): Sources of Power');
INSERT INTO Courses VALUES('LW21016','Public Law III - Rights and Freedoms');
INSERT INTO Courses VALUES('LW22012','English Criminal Law and Evidence');
INSERT INTO Courses VALUES('LW22013','English Law of Tort');
INSERT INTO Courses VALUES('LW22014','Public Law II (Advanced): Controls on Power');
INSERT INTO Courses VALUES('LW22015','Law, Society and Human Rights');
INSERT INTO Courses VALUES('LW22016','Roman Law');
INSERT INTO Courses VALUES('LW22019','Scottish Family Law');
INSERT INTO Courses VALUES('LW22020','Law, Technology and Innovation');
INSERT INTO Courses VALUES('LW22021','Creating your Future: Innovation, Careers and Enterprise');
INSERT INTO Courses VALUES('LW31002','Justice, Law and Human Rights');
INSERT INTO Courses VALUES('LW31003','Law, Family and Society');
INSERT INTO Courses VALUES('LW31010','Employment Law');
INSERT INTO Courses VALUES('LW31015','Planning Law');
INSERT INTO Courses VALUES('LW31023','Criminal Procedure');
INSERT INTO Courses VALUES('LW31024','Private International Law');
INSERT INTO Courses VALUES('LW31026','English Law of Obligations');
INSERT INTO Courses VALUES('LW31030','English Law of Equity and Trusts');
INSERT INTO Courses VALUES('LW31031','Public Law III - Rights and Freedoms (Advanced)');
INSERT INTO Courses VALUES('LW31033','Foundations of International Criminal Law');
INSERT INTO Courses VALUES('LW31035','Legal History');
INSERT INTO Courses VALUES('LW31036','Commercial Law (Advanced)');
INSERT INTO Courses VALUES('LW31038','Law in Practice');
INSERT INTO Courses VALUES('LW31039','Taxation Law');
INSERT INTO Courses VALUES('LW31040','Energy Projects and Environmental Law');
INSERT INTO Courses VALUES('LW31041','Promoting Freedom of Information');
INSERT INTO Courses VALUES('LW32016','International Law');
INSERT INTO Courses VALUES('LW32020','Real Estate and Commercial Practice');
INSERT INTO Courses VALUES('LW32026','Company Law');
INSERT INTO Courses VALUES('LW32027','Intellectual Property Law');
INSERT INTO Courses VALUES('LW32028','English Law of Property');
INSERT INTO Courses VALUES('LW32032','Reparation');
INSERT INTO Courses VALUES('LW32035','Comparative Constitutional Law');
INSERT INTO Courses VALUES('LW40001','Dissertation');
INSERT INTO Courses VALUES('LW40002','Moot');
INSERT INTO Courses VALUES('LW41001','Company Law (Advanced)');
INSERT INTO Courses VALUES('LW41015','Private International Law (Advanced)');
INSERT INTO Courses VALUES('LW41016','Justice, Law and Human Rights (Advanced)');
INSERT INTO Courses VALUES('LW41017','English Law of Obligations (Advanced)');
INSERT INTO Courses VALUES('LW41018','International Law');
INSERT INTO Courses VALUES('LW41019','English Law of Equity and Trusts (Dual Qualifying )');
INSERT INTO Courses VALUES('LW41020','Employment Law (Advanced)');
INSERT INTO Courses VALUES('LW41022','Planning Law (Advanced)');
INSERT INTO Courses VALUES('LW41024','Foundations of International Criminal Law (Advanced)');
INSERT INTO Courses VALUES('LW41025','Legal History (Advanced)');
INSERT INTO Courses VALUES('LW41027','Law in Practice');
INSERT INTO Courses VALUES('LW41028','Taxation Law (Advanced)');
INSERT INTO Courses VALUES('LW41029','Energy Projects and Environmental Law (Advanced)');
INSERT INTO Courses VALUES('LW41030','Promoting Freedom of Information (Advanced)');
INSERT INTO Courses VALUES('LW42010','Intellectual Property Law');
INSERT INTO Courses VALUES('LW42019','Real Estate and Commercial Practice');
INSERT INTO Courses VALUES('LW42023','Law, Family and Society');
INSERT INTO Courses VALUES('LW42024','English Law of Property (DQ)');
INSERT INTO Courses VALUES('LW42026','Criminal Procedure (Advanced)');
INSERT INTO Courses VALUES('LW42029','Reparation (Advanced)');
INSERT INTO Courses VALUES('LW42032','Comparative Constitutional Law and Comparative Constitutional Law (Advanced)');
INSERT INTO Courses VALUES('LW50107','Masters Dissertation');
INSERT INTO Courses VALUES('LW50108','Legal Research Skills');
INSERT INTO Courses VALUES('LW51007','Corporate Governance');
INSERT INTO Courses VALUES('LW51111','Private International Law of Business Transactions');
INSERT INTO Courses VALUES('LW51115','Environmental Regulation');
INSERT INTO Courses VALUES('LW51117','International Family Law');
INSERT INTO Courses VALUES('LW51120','International Criminal Justice');
INSERT INTO Courses VALUES('LW51123','International Law & Security');
INSERT INTO Courses VALUES('LW51127','Transnational Crime and Counter Terrorism');
INSERT INTO Courses VALUES('LW51128','Global Human Rights: Traditions and Inspirations');
INSERT INTO Courses VALUES('LW51133','Private International Law (Common Law Perspectives)');
INSERT INTO Courses VALUES('LW51144','Public International Law');
INSERT INTO Courses VALUES('LW51145','Legal Frameworks for Water Resource Management');
INSERT INTO Courses VALUES('LW51146','International Investment Law');
INSERT INTO Courses VALUES('LW52003','Principles of Corporate Law');
INSERT INTO Courses VALUES('LW52004','Banking Law and Financial Markets');
INSERT INTO Courses VALUES('LW52005','Competition Law');
INSERT INTO Courses VALUES('LW52006','Sustainable Development');
INSERT INTO Courses VALUES('LW52011','Regional Human Rights Systems');
INSERT INTO Courses VALUES('LW52022','UN Human Rights Law');
INSERT INTO Courses VALUES('LW52024','International Law of Marine Resources');
INSERT INTO Courses VALUES('LW52103','Principles of E-Commerce Law');
INSERT INTO Courses VALUES('LW52111','Intellectual Property Law');
INSERT INTO Courses VALUES('LW52115','Ecosystems and International Law');
INSERT INTO Courses VALUES('LW52122','International Dispute Resolution');
INSERT INTO Courses VALUES('LW52132','World Trade Organisation Law');
INSERT INTO Courses VALUES('LW52135','International Taxation Law');
INSERT INTO Courses VALUES('LW52138','Governance and Regulation of Water Services');
INSERT INTO Courses VALUES('LW52140','International Climate Change Law');
INSERT INTO Courses VALUES('DS50009','Research project');
INSERT INTO Courses VALUES('DS50010','Advanced Endodontic practice');
INSERT INTO Courses VALUES('DS50011','Dissertation');
INSERT INTO Courses VALUES('DS51001','Introduction to Prosthodontics');
INSERT INTO Courses VALUES('DS51002','Complete Dentures');
INSERT INTO Courses VALUES('DS51003','Management of Dental Caries and the Vital Pulp');
INSERT INTO Courses VALUES('DS51004','Endodontics aspects');
INSERT INTO Courses VALUES('DS51005','Indirect fixed Prosthodontics');
INSERT INTO Courses VALUES('DS51006','Orthodontic Treatment mechanics');
INSERT INTO Courses VALUES('DS51007','Research methods and dissertation');
INSERT INTO Courses VALUES('DS51008','Dental Public Health');
INSERT INTO Courses VALUES('DS51012','Foundation of endodontics');
INSERT INTO Courses VALUES('DS51013','Nonsurgical endodontic treatment');
INSERT INTO Courses VALUES('DS52001','Partial Dentures');
INSERT INTO Courses VALUES('DS52002','Applied Dental Materials');
INSERT INTO Courses VALUES('DS52004','Comprehensive prosthodontic cases');
INSERT INTO Courses VALUES('DS52005','Craniofacial Growth and Development and the Aetiology of Malocclusion');
INSERT INTO Courses VALUES('DS52006','Tooth movement and biomechanics');
INSERT INTO Courses VALUES('DS52007','Orthodontic materials and health & safety');
INSERT INTO Courses VALUES('DS52009','Health Promotion');
INSERT INTO Courses VALUES('DS52008','Adult and multidisciplinary treatment');
INSERT INTO Courses VALUES('DS52010','Oral Epidemiology');
INSERT INTO Courses VALUES('DS52011','Preparing for the Dissertation');
INSERT INTO Courses VALUES('DS52015','Endodontic treatment');
INSERT INTO Courses VALUES('DS52016','Periapical surgery');
INSERT INTO Courses VALUES('DS52017','Clinical Restorative Dental Care 1');
INSERT INTO Courses VALUES('DS52018','Understanding Evidence and Reflection as Integral to Learning and Clinical Capability');
INSERT INTO Courses VALUES('DS52019','Leadership and Management when delivering Restorative Dental Care');
INSERT INTO Courses VALUES('DS52020','Clinical Restorative Dental Care 2');
INSERT INTO Courses VALUES('DS52021','Communication when delivering Restorative Dental Care');
INSERT INTO Courses VALUES('DS52022','Professionalism when delivering Restorative Dental Care');
INSERT INTO Courses VALUES('DS52023','Oro-facial aesthetics and cosmesis');
INSERT INTO Courses VALUES('DS52024','Evidence-Based Dentistry for Restorative Dental Care');
INSERT INTO Courses VALUES('DS53001','Assessment, Diagnosis and Treatment Planning');
INSERT INTO Courses VALUES('DS53002','Dissertation');
INSERT INTO Courses VALUES('DS5001','Preparing for Specialist Practice');
INSERT INTO Courses VALUES('DS52025','Project for dental TPG programmes');
INSERT INTO Courses VALUES('DS50024','Academic writing and communicating science in dentistry');
INSERT INTO Courses VALUES('GM5011','MREs Oral Cancer: Research Module');
INSERT INTO Courses VALUES('GM51005-1','Palliative Care: Foundations and Research (Part 1)');
INSERT INTO Courses VALUES('GM51005-2','Palliative Care: Foundations and Research (Part 2)');
INSERT INTO Courses VALUES('GM51010','Clinical Statistics');
INSERT INTO Courses VALUES('GM51011','Epidemiology');
INSERT INTO Courses VALUES('GM51012','Public Health');
INSERT INTO Courses VALUES('GM51040','Behavioural and Social Science');
INSERT INTO Courses VALUES('GM51045','Oral cancer Aeteology: Diagnosis and Management');
INSERT INTO Courses VALUES('GM51053','Fundamental Science in Assisted Reproductive Techniques');
INSERT INTO Courses VALUES('GM51066','Scientific Method');
INSERT INTO Courses VALUES('GM51067','Molecular and Cellular Biology of Cancer');
INSERT INTO Courses VALUES('GM51068','Cancer Development, Progression, and Treatment');
INSERT INTO Courses VALUES('GM51071','Basic Laboratory Skills');
INSERT INTO Courses VALUES('GM51072','Foundations in Neuroscience');
INSERT INTO Courses VALUES('GM51073','Advanced Technologies in Neuroscience');
INSERT INTO Courses VALUES('GM51074','Mechanisms and Disorders of Memory');
INSERT INTO Courses VALUES('GM51075','Translational Neuroscience');
INSERT INTO Courses VALUES('GM52003','Research Project');
INSERT INTO Courses VALUES('GM52006','Applied Statistics with Routine Health Datasets');
INSERT INTO Courses VALUES('GM52007','Statistics for Clinical Trials');
INSERT INTO Courses VALUES('GM52008','Research Methods');
INSERT INTO Courses VALUES('GM52011','Spatial Epidemiology');
INSERT INTO Courses VALUES('GM52017','Applied Epidemiology');
INSERT INTO Courses VALUES('GM52019','Introduction to Systematic Reviews');
INSERT INTO Courses VALUES('GM52020','Data Visualization');
INSERT INTO Courses VALUES('GM52035','Running a Successful ART Laboratory and Clinical Service');
INSERT INTO Courses VALUES('GM52036','Clinical Issues and Controversies in ART');
INSERT INTO Courses VALUES('GM52040','Advanced Laboratory Skills');
INSERT INTO Courses VALUES('GM53003','Dissertation');
INSERT INTO Courses VALUES('GM53009','Research Project');
INSERT INTO Courses VALUES('GM53017','Research Project in Neuroscience');
INSERT INTO Courses VALUES('MA11001','Mathematics 1A');
INSERT INTO Courses VALUES('MA12001','Mathematics 1B');
INSERT INTO Courses VALUES('MA12002','Topics in Pure Mathematics');
INSERT INTO Courses VALUES('MA12003','Statistics and Probability');
INSERT INTO Courses VALUES('MA21001','Mathematics 2A');
INSERT INTO Courses VALUES('MA21002','Computer Algebra and Dynamical Systems');
INSERT INTO Courses VALUES('MA21003','Discrete Mathematics');
INSERT INTO Courses VALUES('MA22001','Mathematics 2B');
INSERT INTO Courses VALUES('MA22004','Statistics and Probability II');
INSERT INTO Courses VALUES('MA31002','Differential Equations');
INSERT INTO Courses VALUES('MA31007','Vector Calculus');
INSERT INTO Courses VALUES('MA32001','Analysis');
INSERT INTO Courses VALUES('MA32003','Operational Research');
INSERT INTO Courses VALUES('MA32005','Fundamentals of Scientific Computing');
INSERT INTO Courses VALUES('MA32006','Complex Analysis');
INSERT INTO Courses VALUES('MA32007','Differential Geometry');
INSERT INTO Courses VALUES('MA32009','Mathematical Biology I');
INSERT INTO Courses VALUES('MA40001','Personal Transferable Skills and Project');
INSERT INTO Courses VALUES('MA41003','Ordinary Differential Equations and Their Approximation');
INSERT INTO Courses VALUES('MA41006','Mathematics of Fluids and Plasmas I: Fluid Dynamics');
INSERT INTO Courses VALUES('MA41007','Graph Theory');
INSERT INTO Courses VALUES('MA42002','Mathematical Biology II');
INSERT INTO Courses VALUES('MA42003','Partial Differential Equations And Their Approximation');
INSERT INTO Courses VALUES('MA42007','Mathematics of Fluids and Plasmas II: MHD and the Sun');
INSERT INTO Courses VALUES('MA50001','Personal Transferable Skills and Project');
INSERT INTO Courses VALUES('MA51003','Dynamical Systems');
INSERT INTO Courses VALUES('MA51004','Computational Modelling and Programming');
INSERT INTO Courses VALUES('MA51005','Stochastic Processes');
INSERT INTO Courses VALUES('MA51006','Inverse Problems');
INSERT INTO Courses VALUES('MA51007','Measure Theory');
INSERT INTO Courses VALUES('MA52001','Mathematical Oncology');
INSERT INTO Courses VALUES('MA52002','Mathematical Ecology and Epidemiology');
INSERT INTO Courses VALUES('MA52003','Mathematical Physiology');
INSERT INTO Courses VALUES('MA52004','Optimization in Finance and Energy');
INSERT INTO Courses VALUES('MA52005','Advanced Fluid Dynamics');
INSERT INTO Courses VALUES('MA52006','Functional Analysis');
INSERT INTO Courses VALUES('MA53002','MSc Project Module');
INSERT INTO Courses VALUES('MA53003','MSc Project Module');
INSERT INTO Courses VALUES('NB30110','Symptom Management in Palliative Care');
INSERT INTO Courses VALUES('NB30101','Acute and Critical Care');
INSERT INTO Courses VALUES('NB30052','Microbiology and its Application to Practice');
INSERT INTO Courses VALUES('NB30102','Communication Issues in Palliative Care');
INSERT INTO Courses VALUES('NB30103','Current Perspectives in Cardiovascular Disease');
INSERT INTO Courses VALUES('NB30104','Developing Academic Skills for Practice');
INSERT INTO Courses VALUES('NB30053','Infection Prevention and Control in Practice');
INSERT INTO Courses VALUES('NB30105','Introduction to Research Based Practice (Core Module)');
INSERT INTO Courses VALUES('NB30107','Meeting the Needs of Older People in Diverse Care Settings');
INSERT INTO Courses VALUES('NB30005','Non-Medical Prescribing (Bachelors)');
INSERT INTO Courses VALUES('NB30108','Person-Centred Approaches to Care');
INSERT INTO Courses VALUES('NB30109','Quality and Clinical Governance in Practice');
INSERT INTO Courses VALUES('NB40100','Project Module');
INSERT INTO Courses VALUES('NB30114','Health and Physical Assessment');
INSERT INTO Courses VALUES('NB30115','Understanding Research and Statistics');
INSERT INTO Courses VALUES('NB30116','Leadership in Practice');
INSERT INTO Courses VALUES('NB30117','Healthcare Ethics and Law');
INSERT INTO Courses VALUES('NB30118','Quality Improvement and Patient Safety');
INSERT INTO Courses VALUES('NB30119','Learning and Teaching for Practice');
INSERT INTO Courses VALUES('NB30120','Contemporary Practice in Palliative Care');
INSERT INTO Courses VALUES('NB30121','Managing the Complexities of Older People''s Healthcare');
INSERT INTO Courses VALUES('NB30006','Mentorship Preparation Programme');
INSERT INTO Courses VALUES('NB30122','Minor Illness Management');
INSERT INTO Courses VALUES('NB30126','COPD and Spirometry');
INSERT INTO Courses VALUES('NB30127','Mental Health for Primary Care');
INSERT INTO Courses VALUES('NB30124','Assessment of Joint Pain');
INSERT INTO Courses VALUES('NB30125','Cardiovascular Disease');
INSERT INTO Courses VALUES('NB30123','Academic Recognition for Professional Learning');
INSERT INTO Courses VALUES('NB30130','Work Based Skills and Innovative Practice (SCQF Level 9)');
INSERT INTO Courses VALUES('NB40131','Work Based Skills and Innovative Practice (SCQF Level 10)');
INSERT INTO Courses VALUES('NB30128','Practical Aspects of Cancer Care (Level 9)');
INSERT INTO Courses VALUES('NB40129','Practical Aspects of Cancer Care (Level 10)');
INSERT INTO Courses VALUES('PY11001','Introductory Psychology 1');
INSERT INTO Courses VALUES('PY12002','Introductory Psychology 2');
INSERT INTO Courses VALUES('PY21001','Understanding the Mind');
INSERT INTO Courses VALUES('PY22002','Individual Development');
INSERT INTO Courses VALUES('PY31001','Cognition');
INSERT INTO Courses VALUES('PY31002','Biological Psychology');
INSERT INTO Courses VALUES('PY31003','Social Psychology');
INSERT INTO Courses VALUES('PY31004','Research Skills 3a');
INSERT INTO Courses VALUES('PY32001','Individual Differences and Abnormal Psychology');
INSERT INTO Courses VALUES('PY32002','Psychology of Language');
INSERT INTO Courses VALUES('PY32003','Developmental Psychology');
INSERT INTO Courses VALUES('PY32004','Research Skills 3b');
INSERT INTO Courses VALUES('PY40042','Developing Complex Cognition');
INSERT INTO Courses VALUES('PY40008','Infant Development');
INSERT INTO Courses VALUES('PY40018','Developmental Psychopathology');
INSERT INTO Courses VALUES('PY40024','Decision Making');
INSERT INTO Courses VALUES('PY40025','Second Language Processing');
INSERT INTO Courses VALUES('PY40028','Gesture, Cognition and Communication');
INSERT INTO Courses VALUES('PY40029','Foundations of Adult Mental Health');
INSERT INTO Courses VALUES('PY40031','The Development of Self-Awareness');
INSERT INTO Courses VALUES('PY40034','Evolution and Behaviour');
INSERT INTO Courses VALUES('PY40036','Society, Mind and Health');
INSERT INTO Courses VALUES('PY40039','Comparative Communication and Cognition');
INSERT INTO Courses VALUES('PY40041','Social, Emotional and Moral Development');
INSERT INTO Courses VALUES('PY41003','Psychology of Music');
INSERT INTO Courses VALUES('PY42001','Self-Regulation');
INSERT INTO Courses VALUES('PY50003','Research in Practice');
INSERT INTO Courses VALUES('PY50031','The Development of Self-Awareness 2');
INSERT INTO Courses VALUES('PY50404','Reading Development and Disability');
INSERT INTO Courses VALUES('PY50418','Developmental Psychopathology 2');
INSERT INTO Courses VALUES('PY50424','Decision Making');
INSERT INTO Courses VALUES('PY50428','Gesture, Cognition and Communication');
INSERT INTO Courses VALUES('PY50429','Foundations of Adult Mental Health');
INSERT INTO Courses VALUES('PY50432','Current Issues in Psychological Health Care');
INSERT INTO Courses VALUES('PY50434','Evolution and Behaviour');
INSERT INTO Courses VALUES('PY50436','Society, Mind and Health');
INSERT INTO Courses VALUES('PY50437','Executive Functions across the Lifespan');
INSERT INTO Courses VALUES('PY50439','Comparative Communication and Cognition');
INSERT INTO Courses VALUES('PY50441','Social, Emotional and Moral Development');
INSERT INTO Courses VALUES('PY51001','Research Foundations');
INSERT INTO Courses VALUES('PY51002','Qualitative Research Methods');
INSERT INTO Courses VALUES('PY51017','Psychology of Music');
INSERT INTO Courses VALUES('PY52004','Research Dissertation');
INSERT INTO Courses VALUES('PY52004a','Research Dissertation POMH');
INSERT INTO Courses VALUES('PY52007','Advanced Quantitative Methods');
INSERT INTO Courses VALUES('PY52009','Self-Regulation');
INSERT INTO Courses VALUES('PY54008','Infant Development');
INSERT INTO Courses VALUES('PY5XXX1',' Individual differences');
INSERT INTO Courses VALUES('PY5XXX2',' Biological psychology');
INSERT INTO Courses VALUES('PY5XXX3',' Social psychology');
INSERT INTO Courses VALUES('PY5XXX4','Cognition');
INSERT INTO Courses VALUES('PY5XXX5','Developmental Psychology');
INSERT INTO Courses VALUES('PY5XXX6',' Psychology of Language');
INSERT INTO Courses VALUES('PY5XXX7','Psychological research skills A');
INSERT INTO Courses VALUES('PY5XXX8','Psychological research skills B');
INSERT INTO Courses VALUES('PY5XXX9','Research Project');
INSERT INTO Courses VALUES('PY51016','Development of Complex Cognition');
INSERT INTO Courses VALUES('PY50001','The Development of Self-Awareness');
INSERT INTO Courses VALUES('ME51006','Biomechanical Systems');
INSERT INTO Courses VALUES('ME51008','Biomaterials');
INSERT INTO Courses VALUES('ME51011','Bioinstrumentation');
INSERT INTO Courses VALUES('ME52001','Advanced Medical and Surgical Technologies');
INSERT INTO Courses VALUES('ME52002','Biomedical Engineering Project');
INSERT INTO Courses VALUES('ME52004','Advanced Biomedical Imaging Technologies');
INSERT INTO Courses VALUES('ME52005','Advanced manufacturing');
INSERT INTO Courses VALUES('ME51013','Advanced Robotics');
INSERT INTO Courses VALUES('ME53001','Engineering Project and Report (Industrial Placement)');
INSERT INTO Courses VALUES('ME12001','Thermodynamics');
INSERT INTO Courses VALUES('ME22002','Mechanics of Machines');
INSERT INTO Courses VALUES('ME40006','Biomedical Research Frontiers');
INSERT INTO Courses VALUES('ME42001','Medical devices and Professional Skills');
INSERT INTO Courses VALUES('ME41003','Medical Ultrasound System');
INSERT INTO Courses VALUES('ME40003','Robotics and Mechatronics (elective module)');
INSERT INTO Courses VALUES('ME40001','Computer Aided Engineering (elective module)');
INSERT INTO Courses VALUES('ME41002','Biomedical Engineering Project 2');
INSERT INTO Courses VALUES('GE11001','Introduction to Geography Part 1: The Unequal World');
INSERT INTO Courses VALUES('GE12002','Introduction to Geography Part 2: Environment, City and Society');
INSERT INTO Courses VALUES('GE21001','Dynamic Human Worlds: Society, Culture, Economy');
INSERT INTO Courses VALUES('GE22002','Dynamic Physical Worlds: Earth, Ice and Water');
INSERT INTO Courses VALUES('GE22003','Geography Field Course (UK)');
INSERT INTO Courses VALUES('GE31019','Research Methods in Human Geography');
INSERT INTO Courses VALUES('GE31020','Field and Laboratory Skills in Physical Geography');
INSERT INTO Courses VALUES('GE32020','Key Ideas in Geography');
INSERT INTO Courses VALUES('GE32021','Data Handling and Statistics');
INSERT INTO Courses VALUES('GE32026','Polar Environments');
INSERT INTO Courses VALUES('GE42024','Polar Environments - Advanced');
INSERT INTO Courses VALUES('GE52032','Freshwater, Wetlands and Ecosystem Services: Science and Security');
INSERT INTO Courses VALUES('GE51013','Quantitative Research Methods');
INSERT INTO Courses VALUES('GE52010','Qualitative Methods');
INSERT INTO Courses VALUES('GE52030','Research in Practice (placement)');
INSERT INTO Courses VALUES('GE51011','Research Training and Project Planning');
INSERT INTO Courses VALUES('GE52024','Applied GIS and Geospatial Data');
INSERT INTO Courses VALUES('DJ11007','Picture, Symbol, Icon');
INSERT INTO Courses VALUES('DJ11008','Ways of Making');
INSERT INTO Courses VALUES('DJ11009','Ways of Seeing');
INSERT INTO Courses VALUES('DJ12008','Design Methods for Insight Gathering');
INSERT INTO Courses VALUES('DJ12009','Introduction to Social Digital');
INSERT INTO Courses VALUES('DJ21013','Designing Social Networks');
INSERT INTO Courses VALUES('DJ21015','Interiors & Interactions');
INSERT INTO Courses VALUES('DJ22013','Prototyping Digital Futures');
INSERT INTO Courses VALUES('DJ22015','Design for Social Environments');
INSERT INTO Courses VALUES('DJ31035','Interaction Design');
INSERT INTO Courses VALUES('DJ32004','Research and Creative Practice 1');
INSERT INTO Courses VALUES('DJ32005','Design Enterprise 1');
INSERT INTO Courses VALUES('DJ32013','Social Media Apps');
INSERT INTO Courses VALUES('DJ32015','Communication Futures 1');
INSERT INTO Courses VALUES('DJ32016','Design for Narrative Environments');
INSERT INTO Courses VALUES('DJ40009','Personal Honours Project');
INSERT INTO Courses VALUES('DJ41001','Research & Creative Practice 2');
INSERT INTO Courses VALUES('DJ41002','Design Enterprise 2');
INSERT INTO Courses VALUES('DJ41005','Communications Futures 2');
INSERT INTO Courses VALUES('DJ51016','Life Art');
INSERT INTO Courses VALUES('DJ51019','Research Skills & Methods');
INSERT INTO Courses VALUES('DJ51029','Exploring Practice');
INSERT INTO Courses VALUES('DJ51032','Accelerator');
INSERT INTO Courses VALUES('DJ51033','Art, Society & Publics 1');
INSERT INTO Courses VALUES('DJ51034','Artistic Research & Writing');
INSERT INTO Courses VALUES('DJ51036','Changing Populations');
INSERT INTO Courses VALUES('DJ51037','Creative Technologies');
INSERT INTO Courses VALUES('DJ51038','Leadership and Culture');
INSERT INTO Courses VALUES('DJ52010','Prototyping: Insights to Innovation');
INSERT INTO Courses VALUES('DJ52026','Advanced Production');
INSERT INTO Courses VALUES('DJ52027','Going Live');
INSERT INTO Courses VALUES('DJ52031','Studio Practice: Independent project');
INSERT INTO Courses VALUES('DJ52034','Art, Society & Publics 2');
INSERT INTO Courses VALUES('DJ52037','Artistic Research & Writing 2');
INSERT INTO Courses VALUES('DJ52038','Medical Art 1: Contemporary Theory and Practice');
INSERT INTO Courses VALUES('DJ52039','Medical Art 2: Communication and Education');
INSERT INTO Courses VALUES('DJ52040','Business Enterprise and Entrepreneurship');
INSERT INTO Courses VALUES('DJ52041','Marketing and Management Strategy');
INSERT INTO Courses VALUES('DJ53002','A&V Realisation');
INSERT INTO Courses VALUES('DJ53006','MSc Dissertation');
INSERT INTO Courses VALUES('DJ53010','Research Through Design');
INSERT INTO Courses VALUES('DJ53011','Masters Art, Society & Publics 3');
INSERT INTO Courses VALUES('DJ53014','Master''s Placement');
